### ISSUE TITLE
ILMergeGUI

### ISSUE THREAD

**Issue by jerem2st** [jpdillingham/ILMergeGUI#1]
Hello, how to build your project ILMergeGUI, i have an exeption 
System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by jpdillingham** [comment]
I can't reproduce the problem on any of my machines.  Try running Visual Studio as an administrator?

**Comment by jerem2st** [comment]
I already work as an administrator but the problem is at the line :
this.TxtLogFile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.FileSystem;

**Comment by jpdillingham** [comment]
Take a look at lines 199-204 here: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/TextBox.cs,c6c1d902e9e45cd4

I haven't encountered this issue nor can I reproduce it, but it does certainly seem like something in your environment is denying the requested access.

Do you encounter this exception on build, or at runtime? 

Is there anything else you can tell me about your environment?

**Comment by jerem2st** [comment]
Yes when i build.
I use VS2015 in administrator (Windows 10)
I have no issue for the moment

Is it possible to have the .exe built to test it ?

**Comment by jpdillingham** [comment]
There's a release with a zip of the binaries [here](https://github.com/jpdillingham/ILMergeGUI/releases)

**Comment by jerem2st** [comment]
thank you very much I will test this :)
