### ISSUE TITLE
Cannot merge .NET 4.8 with ILMerge

### ISSUE THREAD

**Issue by Thomas-Dayman** [jpdillingham/ILMergeGUI#6]
![image](https://user-images.githubusercontent.com/41510856/73088655-93ac1400-3ecc-11ea-83c9-0657eabdd1dc.png)

I am trying to merge two .dll files into one but I cannot merge my assemblies anymore due to this issue in the image above

**Comment by jpdillingham** [comment]
Relevant code is here: https://github.com/jpdillingham/ILMergeGUI/blob/master/ILMergeGui/Mainform.cs#L1236

Unfortunately this is a pretty generic error condition.  @BobVul last updated this to work with 4.8 but I personally never tested; I suspect the issue isn't with the framework version itself but rather something in your binaries.

If you could debug the app and grab the Exception, that would be helpful.

You might also try to merge with the CLI and see if that gives a more descriptive message.

**Comment by Thomas-Dayman** [comment]
I got it to work by downloading the source code and running it in Visual Studio. then it gave me the option for 4.8

![image](https://user-images.githubusercontent.com/41510856/73161641-e6134d80-40e3-11ea-971d-d2b818446ad9.png)
