### ISSUE TITLE
Download ILMergeGUI 2.0.11.0 zip, show error msg.

### ISSUE THREAD

**Issue by ghost** [jpdillingham/ILMergeGUI#7]
This is a error msg:
![image](https://user-images.githubusercontent.com/23723575/97946229-c15fab00-1dc4-11eb-936e-d455e101ff47.png)

Tips: Location language is zh-CN.

**Comment by jpdillingham** [comment]
You will need to download the ILMerge binaries from [here](https://www.nuget.org/packages/ilmerge) and copy the files `ILMerge.exe` and `System.Compiler.dll` into the directory containing `ILMergeGui.exe`.

You can do this by extracting the nuget package as a zip file (with 7-zip or similar); the files you need to copy are located in `tools\net452`

**Comment by ghost** [comment]
Out of box is very important, I think. Could you make a full installer for user, that is a very good idea.
